WebUniversity/WebUniversity/ViewModels/CourseViewModel.cs
using System.ComponentModel.DataAnnotations;
using WebUniversity.DataLayer;
using WebUniversity.DataLayer.Entity;

namespace WebUniversity.ViewModels
{
    public class CourseViewModel
    {
        [Display(Name = "Id")]
        [UIHint("number")]
        public int Id { get; set; }

        [Display(Name = "Name")]
        [UIHint("text")]
        [Required(ErrorMessage = "Enter name of the course")]
        [MinLength(5, ErrorMessage = "Name of a course must be more 5 symbols")]
        [RegularExpression(@"^[A-Za-z'\s0-9]+$", ErrorMessage = "Invalid characters")]
        public string Name { get; set; }

        [Display(Name = "Description")]
        [UIHint("text")]
        public string Description { get; set; }

        public PaginatedList<Group>? Mygroups { get; set; }

        public bool HasGroups { get; set; }

        public CourseViewModel()
        {
            HasGroups = false;
        }
    }
}

WebUniversity/WebUniversity/Controllers/CourseController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebUniversity.DataLayer;
using WebUniversity.DataLayer.Entity;
using WebUniversity.DataLayer.UnitOfWork;
using WebUniversity.ViewModels;

namespace WebUniversity.Controllers
{
    public class CourseController : EntityController<Course>
    {
        public CourseController(ILogger<CourseController> logger, IUnitOfWork<StateDbContext> unitOfWork, IMapper mapper) : base(logger, unitOfWork, mapper)
        {
        }

        [HttpGet]
        public async Task<IActionResult> Index(string sortOrder, string currentFilter, string searchString, int? pageNumber)
        {
            var courses = _repository.GetAll();

            ViewData["CurrentSort"] = sortOrder;
            ViewData["IdSortParm"] = String.IsNullOrEmpty(sortOrder) ? "Id_desc" : "";
            ViewData["NameSortParm"] = sortOrder == "Name" ? "name_desc" : "Name";

            Filter(ref courses, currentFilter, searchString, ref pageNumber);

            Sort(ref courses, sortOrder);

            int pageSize = jsonObject.PageSettings.PageSize.ToObject<int>();
            return View(await PaginatedList<CourseViewModel>.CreateAsync(courses.Select(x => _mapper.Map<CourseViewModel>(x)).AsNoTracking(), pageNumber ?? 1, pageSize));
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CourseViewModel newCourse)
        {
            if (ModelState.IsValid)
            {
                _repository.Insert(_mapper.Map<Course>(newCourse));

                return RedirectToAction("Index");
            }

            return View(newCourse);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            return View(_mapper.Map<CourseViewModel>(_repository.Find(id)));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(CourseViewModel changedCourse)
        {
            if (ModelState.IsValid)
            {
                _repository.Update(_mapper.Map<Course>(changedCourse));

                return RedirectToAction("Index");
            }

            return View(changedCourse);
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            CourseViewModel course = _mapper.Map<CourseViewModel>(_repository.Find(id));
            course.Mygroups = new PaginatedList<Group>(_unitOfWork.GetRepository<Group>().GetAll(x => x.CourseID == course.Id).ToList(), 0, 1, 0);

            if (course.Mygroups != null && course.Mygroups.Count > 0)
            {
                course.HasGroups = true;
            }

            return View(course);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(CourseViewModel changedCourse)
        {
            if (changedCourse.HasGroups)
            {
                ViewData["messageIsGroups"] = "You do not can delete this course, because It contain groups.";

                return View(changedCourse);
            }

            _repository.Delete(_mapper.Map<Course>(changedCourse));

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id, string sortOrder, string currentFilter, string searchString, int? pageNumber)
        {
            CourseViewModel course = _mapper.Map<CourseViewModel>(_repository.Find(id));
            var groups = _unitOfWork.GetRepository<Group>().GetAll();
            groups = groups.Where(g => g.CourseID == id);

            ViewData["CurrentSort"] = sortOrder;
            ViewData["IdSortParm"] = String.IsNullOrEmpty(sortOrder) ? "Id_desc" : "";
            ViewData["NameSortParm"] = sortOrder == "Name" ? "name_desc" : "Name";

            Filter(ref groups, currentFilter, searchString, ref pageNumber);

            GroupController.Sort(ref groups, sortOrder);

            int pageSize = jsonObject.PageSettings.PageSize.ToObject<int>();
            course.Mygroups = await PaginatedList<Group>.CreateAsync(groups.AsQueryable().AsNoTracking(), pageNumber ?? 1, pageSize);

            return View(course);
        }

        private void Sort(ref IQueryable<Course> courses, string sortOrder)
        {
            switch (sortOrder)
            {
                case "id_desc":
                    courses = courses.OrderByDescending(c => c.Id);
                    break;
                case "Name":
                    courses = courses.OrderBy(c => c.Name);
                    break;
                case "name_desc":
                    courses = courses.OrderByDescending(c => c.Name);
                    break;
                default:
                    courses = courses.OrderBy(c => c.Id);
                    break;
            }
        }
    }
}

WebUniversity/WebUniversity/Controllers/GroupController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebUniversity.DataLayer;
using WebUniversity.DataLayer.Entity;
using WebUniversity.DataLayer.UnitOfWork;
using WebUniversity.ViewModels;

namespace WebUniversity.Controllers
{
    public class GroupController : EntityController<Group>
    {
        public GroupController(ILogger<GroupController> logger, IUnitOfWork<StateDbContext> unitOfWork, IMapper mapper) : base(logger, unitOfWork, mapper)
        {
        }

        [HttpGet]
        public async Task<IActionResult> Index(string sortOrder, string currentFilter, string searchString, int? pageNumber)
        {
            ViewData["CurrentSort"] = sortOrder;
            ViewData["IdSortParm"] = String.IsNullOrEmpty(sortOrder) ? "Id_desc" : "";
            ViewData["NameSortParm"] = sortOrder == "Name" ? "name_desc" : "Name";
            ViewData["CourseIdSortParm"] = sortOrder == "CourseId" ? "courseId_desc" : "CourseId";
            var groups = _repository.GetAll().Include(g => g.Course).AsQueryable();



            Filter(ref groups, currentFilter, searchString, ref pageNumber);

            Sort(ref groups, sortOrder);

            int pageSize = jsonObject.PageSettings.PageSize.ToObject<int>();
            return View(await PaginatedList<GroupViewModel>.CreateAsync(groups.Select(x => _mapper.Map<GroupViewModel>(x)).AsNoTracking(), pageNumber ?? 1, pageSize));
        }

        [HttpGet]
        public IActionResult Create(int CourseId)
        {
            var existingCourse = _unitOfWork.GetRepository<Course>().GetAll().Select(x => new SelectListItem { Value = $"{x.Id}", Text = $"{x.Id} {x.Name}" });
            GroupViewModel newGroup = new();
            newGroup.existingCourses = existingCourse.ToList();

            newGroup.CourseID = CourseId;

            return View(newGroup);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(GroupViewModel newGroup)
        {
            if (ModelState.IsValid)
            {
                _repository.Insert(_mapper.Map<Group>(newGroup));

                return RedirectToAction("Details", "Course", new { id = newGroup.CourseID });
            }

            return View(newGroup);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var existingCourse = _unitOfWork.GetRepository<Course>().GetAll().Select(x => new SelectListItem { Value = $"{x.Id}", Text = $"{x.Id} {x.Name}" });
            GroupViewModel group = _mapper.Map<GroupViewModel>(_repository.Find(id));
            group.existingCourses = existingCourse.ToList();

            return View(group);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(GroupViewModel changedGroup)
        {
            if (ModelState.IsValid)
            {
                _repository.Update(_mapper.Map<Group>(changedGroup));

                return RedirectToAction("Index");
            }

            return View(changedGroup);
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            GroupViewModel group = _mapper.Map<GroupViewModel>(_repository.Find(id));
            group.MyStudents = new PaginatedList<Student>(_unitOfWork.GetRepository<Student>().GetAll(x => x.GroupId == group.Id).ToList(), 0, 1, 0);

            if (group.MyStudents != null && group.MyStudents.Count > 0)
            {
                group.HasStudents = true;
            }

            return View(group);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(GroupViewModel group)
        {
            if (group.HasStudents)
            {
                ViewData["messageIsStudents"] = "You do not can delete this group, because It contain students.";
                return View(group);
            }

            _repository.Delete(_mapper.Map<Group>(group));

            return RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Details(int id, string sortOrder, string currentFilter, string searchString, int? pageNumber)
        {
            var group = _mapper.Map<GroupViewModel>(_repository.Find(id));
            var students = _unitOfWork.GetRepository<Student>().GetAll();
            students = students.Where(student => student.GroupId == id);

            ViewData["CurrentSort"] = sortOrder;
            ViewData["IdSortParm"] = String.IsNullOrEmpty(sortOrder) ? "Id_desc" : "";
            ViewData["LastNameSortParm"] = sortOrder == "LastName" ? "lastname_desc" : "LastName";
            ViewData["FirstNameSortParm"] = sortOrder == "FirstName" ? "first_desc" : "FirstName";
            ViewData["GroupIdSortParm"] = sortOrder == "GroupId" ? "groupId_desc" : "GroupId";

            Filter(ref students, currentFilter, searchString, ref pageNumber);

            StudentController.Sort(ref students, sortOrder);

            int pageSize = jsonObject.PageSettings.PageSize.ToObject<int>();
            group.MyStudents = await PaginatedList<Student>.CreateAsync(students.AsNoTracking(), pageNumber ?? 1, pageSize);
            return View(group);
        }

        public static void Sort(ref IQueryable<Group> groups, string sortOrder)
        {
            switch (sortOrder)
            {
                case "id_desc":
                    groups = groups.OrderByDescending(c => c.Id);
                    break;
                case "Name":
                    groups = groups.OrderBy(c => c.Name);
                    break;
                case "name_desc":
                    groups = groups.OrderByDescending(c => c.Name);
                    break;
                case "CourseId":
                    groups = groups.OrderBy(c => c.CourseID);
                    break;
                case "courseId_desc":
                    groups = groups.OrderByDescending(c => c.CourseID);
                    break;
                default:
                    groups = groups.OrderBy(c => c.Id);
                    break;
            }
        }
    }
}

WebUniversity/WebUniversity/Views/Course/Create.cshtml
@model CourseViewModel
<link rel="stylesheet" href="~/css/entity-form.css" />

<h1>Create New Course</h1>
<form asp-controller="Course" asp-action="Create" method="post">
    @Html.AntiForgeryToken()
    <fieldset>
        <legend>Course Information</legend>

        <div class="form-group">
            <label asp-for="Name"></label>
            <input asp-for="Name" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="Description"></label>
            <input asp-for="Description" />
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>

        <input type="submit" value="Create" />
    </fieldset>
</form>

WebUniversity/WebUniversity/Views/Course/Delete.cshtml
@model CourseViewModel
@{
    ViewData["Title"] = "Delete Course";
}

<link rel="stylesheet" href="~/css/delete-confirmation.css" />

<div class="delete-container">
    <h1>Confirm Deletion</h1>

    @if (ViewData["messageIsGroups"] != null)
    {
        <div class="warning-message">
            <strong>@ViewData["messageIsGroups"]</strong>
        </div>
    }

    <form asp-controller="Course" asp-action="Delete" method="post">
        @Html.AntiForgeryToken()
        <fieldset>
            <legend>Course Information</legend>

            <div class="field">
                <label asp-for="Id"></label>
                <span class="value">@Model.Id</span>
                <input asp-for="Id" type="hidden" />
            </div>

            <div class="field">
                <label asp-for="Name"></label>
                <span class="value">@Model.Name</span>
                <input asp-for="Name" type="hidden" />
            </div>

            <div class="field">
                <label asp-for="Description"></label>
                <span class="value">@Model.Description</span>
                <input asp-for="Description" type="hidden" />
            </div>

            <input asp-for="HasGroups" type="hidden" />

            <button type="submit" class="btn-confirm">Confirm</button>
        </fieldset>
    </form>
</div>

WebUniversity/WebUniversity/Views/Course/Details.cshtml
@using WebUniversity.ViewModels
@model CourseViewModel

@{
    ViewData["Title"] = "Detail";
}

<head>
    <meta charset="utf-8" />
    <title>Detail of the course</title>
    <link rel="stylesheet" href="~/css/entity-details.css" />
</head>

<hr />
<h4>Course Detail</h4>
<dl class="details-container">
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Id)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Id)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Name)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Name)
    </dd>
    <dt class="col-sm-2">
        @Html.DisplayNameFor(model => model.Description)
    </dt>
    <dd class="col-sm-10">
        @Html.DisplayFor(model => model.Description)
    </dd>
</dl>

<form asp-controller="Group" asp-action="Create" method="get">
    <input type="hidden" name="CourseId" value="@Model.Id" />
    <input type="submit" value="Create new group" class="btn btn-primary" />
</form>

<form asp-action="Index" method="get">
    <div class="form-actions no-color">
        <p>
            Find by name: <input type="text" name="SearchString" value="@ViewData["CurrentFilter"]" />
            <input type="submit" value="Search" class="btn btn-default" /> |
            <a asp-action="Index">Back to Full List</a>
        </p>
    </div>
</form>

<div class="table-responsive">
    <table class="table table-striped">
        <caption>List of groups</caption>
        <thead>
            <tr>
                <th><a asp-action="Details" asp-route-sortOrder="@ViewData["IdSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Id</a></th>
                <th><a asp-action="Details" asp-route-sortOrder="@ViewData["NameSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Name</a></th>
                <th>Course Id</th>
                <th>Actions</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Mygroups)
            {
                <tr>
                    <td>@Html.DisplayFor(modelItem => item.Id)</td>
                    <td>@Html.DisplayFor(modelItem => item.Name)</td>
                    <td>@Html.DisplayFor(modelItem => item.CourseID)</td>
                    <td>
                        <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-sm btn-warning me-1">Edit</a>
                        <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-sm btn-info me-1">Details</a>
                        <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-sm btn-danger">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

@{
    var groupList = Model.Mygroups;
    var prevDisabled = !groupList.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !groupList.HasNextPage ? "disabled" : "";
}

<ul class="pagination">
    <li class="page-item">
        <a asp-action="Details"
           asp-route-sortOrder="@ViewData["CurrentSort"]"
           asp-route-pageNumber="@(groupList.PageIndex - 1)"
           asp-route-currentFilter="@ViewData["CurrentFilter"]"
           class="page-link @prevDisabled">
            Previous
        </a>
    </li>

    <li class="@(groupList.PageIndex == 1 ? "page-item active" : "page-item")">
        <a asp-action="Details"
           asp-route-sortOrder="@ViewData["CurrentSort"]"
           asp-route-pageNumber="1"
           asp-route-currentFilter="@ViewData["CurrentFilter"]"
           class="page-link">
            1
        </a>
    </li>

    @if (groupList.TotalPages > 3 && groupList.PageIndex > 3)
    {
        <p> . . . </p>
    }

    @if (groupList.TotalPages > 3 && groupList.PageIndex > 2 && groupList.PageIndex < groupList.TotalPages)
    {
        <li>
            <a asp-action="Details"
               asp-route-sortOrder="@ViewData["CurrentSort"]"
               asp-route-pageNumber="@(groupList.PageIndex - 1)"
               asp-route-currentFilter="@ViewData["CurrentFilter"]"
               class="page-link">
                @(groupList.PageIndex - 1)
            </a>
        </li>
    }

    @if (groupList.TotalPages > 2)
    {
        <li class="@((groupList.PageIndex > 1 && groupList.PageIndex < groupList.TotalPages) ? "page-item active" : "page-item")">
            <a asp-action="Details"
               asp-route-sortOrder="@ViewData["CurrentSort"]"
               asp-route-pageNumber="@(groupList.PageIndex == 1 ? groupList.PageIndex + 1 : groupList.PageIndex != groupList.TotalPages ? groupList.PageIndex : groupList.TotalPages - 1)"
               asp-route-currentFilter="@ViewData["CurrentFilter"]"
               class="page-link">
                @(groupList.PageIndex == 1 ? groupList.PageIndex + 1 : groupList.PageIndex != groupList.TotalPages ? groupList.PageIndex : groupList.TotalPages - 1)
            </a>
        </li>
    }

    @if (groupList.TotalPages > 3 && groupList.PageIndex < groupList.TotalPages - 1 && groupList.PageIndex > 1)
    {
        <li>
            <a asp-action="Details"
               asp-route-sortOrder="@ViewData["CurrentSort"]"
               asp-route-pageNumber="@(groupList.PageIndex + 1)"
               asp-route-currentFilter="@ViewData["CurrentFilter"]"
               class="page-link">
                @(groupList.PageIndex + 1)
            </a>
        </li>
    }

    @if (groupList.TotalPages > 3 && groupList.PageIndex < groupList.TotalPages - 2)
    {
        <p> . . . </p>
    }

    @if (groupList.TotalPages > 1)
    {
        <li class="@(groupList.PageIndex == groupList.TotalPages ? "page-item active" : "page-item")">
            <a asp-action="Details"
               asp-route-sortOrder="@ViewData["CurrentSort"]"
               asp-route-pageNumber="@groupList.TotalPages"
               asp-route-currentFilter="@ViewData["CurrentFilter"]"
               class="page-link">
                @(groupList.TotalPages)
            </a>
        </li>
    }

    <li>
        <a asp-action="Details"
           asp-route-sortOrder="@ViewData["CurrentSort"]"
           asp-route-pageNumber="@(groupList.PageIndex + 1)"
           asp-route-currentFilter="@ViewData["CurrentFilter"]"
           class="page-link @nextDisabled">
            Next
        </a>
    </li>
</ul>

<div>
    <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-sm btn-warning me-1">Edit</a>
    <a asp-action="Delete" asp-route-id="@Model.Id" class="btn btn-sm btn-danger">Delete</a>
    <a asp-action="Index" class="btn btn-sm btn-info me-1">Back to List</a>
</div>

WebUniversity/WebUniversity/Views/Course/Edit.cshtml
@model CourseViewModel
<link rel="stylesheet" href="~/css/entity-form.css" />

<h1>Edit Course</h1>
<form asp-controller="Course" asp-action="Edit" method="post">
    @Html.AntiForgeryToken()
    <fieldset>
        <legend>Course Information</legend>

        <div class="form-group">
            <label asp-for="Id"></label>
            <strong>@Model.Id</strong>
        </div>

        <div class="form-group">
            <label asp-for="Name"></label>
            <input asp-for="Name" />
            <span asp-validation-for="Name" class="text-danger"></span>
        </div>

        <div class="form-group">
            <label asp-for="Description"></label>
            <input asp-for="Description" />
            <span asp-validation-for="Description" class="text-danger"></span>
        </div>

        <input type="submit" name="buttonSubmit" value="Save changes" />
    </fieldset>
</form>

WebUniversity/WebUniversity/Views/Course/Index.cshtml
@using WebUniversity.DataLayer
@using WebUniversity.ViewModels
@model PaginatedList<CourseViewModel>

@{
    ViewData["Title"] = "Courses";
}

<link rel="stylesheet" href="~/css/entity-index.css" />

<div class="d-flex justify-content-between mb-3">
    <form asp-controller="Course" asp-action="Create" method="get">
        <input type="submit" value="Create New Course" class="btn btn-primary" />
    </form>

    <form asp-action="Index" method="get" class="d-flex">
        <input type="text" name="SearchString" value="@ViewData["CurrentFilter"]" class="form-control me-2" placeholder="Find by name..." />
        <input type="submit" value="Search" class="btn btn-outline-secondary me-2" />
        <a asp-action="Index" class="btn btn-outline-secondary">Reset</a>
    </form>
</div>

<table class="table table-striped">
    <caption>List of Courses</caption>
    <thead>
        <tr>
            <th><a asp-action="Index" asp-route-sortOrder="@ViewData["IdSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Id</a></th>
            <th><a asp-action="Index" asp-route-sortOrder="@ViewData["NameSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">Name</a></th>
            <th>Description</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.Name</td>
                <td>@item.Description</td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-sm btn-warning me-1">Edit</a>
                    <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-sm btn-info me-1">Details</a>
                    <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-sm btn-danger">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

@{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}

<nav aria-label="Page navigation">
    <ul class="pagination">
        <li class="page-item @prevDisabled">
            <a class="page-link" asp-action="Index" asp-route-pageNumber="@(Model.PageIndex - 1)"
               asp-route-sortOrder="@ViewData["CurrentSort"]"
               asp-route-currentFilter="@ViewData["CurrentFilter"]">Previous</a>
        </li>

        @for (int i = 1; i <= Model.TotalPages; i++)
        {
            if (i == 1 || i == Model.TotalPages || (i >= Model.PageIndex - 1 && i <= Model.PageIndex + 1))
            {
                <li class="page-item @(i == Model.PageIndex ? "active" : "")">
                    <a class="page-link" asp-action="Index"
                       asp-route-pageNumber="@i"
                       asp-route-sortOrder="@ViewData["CurrentSort"]"
                       asp-route-currentFilter="@ViewData["CurrentFilter"]">@i</a>
                </li>
            }
            else if ((i == Model.PageIndex - 2 || i == Model.PageIndex + 2))
            {
                <li class="page-item disabled"><span class="page-link">...</span></li>
            }
        }

        <li class="page-item @nextDisabled">
            <a class="page-link" asp-action="Index" asp-route-pageNumber="@(Model.PageIndex + 1)"
               asp-route-sortOrder="@ViewData["CurrentSort"]"
               asp-route-currentFilter="@ViewData["CurrentFilter"]">Next</a>
        </li>
    </ul>
</nav>